<a href="https://colab.research.google.com/github/MXMxRazer/Deep-Learning---Tensors-Learning-In-Progress-/blob/main/PyTourchLearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 0.0 PyTorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [ ]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

print(torch.__version__)

2.1.0+cu118


## Introduction to Tensors

### Creating Tensors

In [ ]:
# Scalar
# Creating tensor with tensor() method with torch "torch.tensor()".
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Convert the tensor to regular data type
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# Matrix
Matrix = torch.tensor([[7, 8],
                      [9, 10]])
Matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
Matrix.ndim

2

In [ ]:
Matrix.shape

torch.Size([2, 2])

In [ ]:
# Tensor
Tensor = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
Tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

### Random Tensors

Random Tensors are important because the way many neural networks learn is that
they start with tensors full of random numbers and then adjust those random
numbers to better represent the data.

```Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers```

In [ ]:
# Create a random tensor with size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.4673, 0.6988, 0.0177, 0.5096],
        [0.7994, 0.2525, 0.7945, 0.1945],
        [0.5154, 0.5972, 0.3789, 0.7721]])

In [ ]:
# Create random tensor with similar size to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # , color channel (R, G, B), height, width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and Ones

In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [ ]:
# Use torch.arange()
one_to_ten = torch.arange(start = 0, end = 11, step = 1)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor DataTypes

In [ ]:
# Float32 tensor
float_32_tensor = torch.tensor([3.0, 6.0],
                               dtype=None, # Data type for Tensor
                               device=None, # Device is your tensor on (Hardware)
                               requires_grad=False) # Track gradients with this tensor operations
float_32_tensor

tensor([3., 6.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6.], dtype=torch.float16)

### Reshaping, Stacking, Squeezing and Unsqueezing Tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack), side by side (hstack)
* Squeeze - removes all `1` dimensions from a tenson
* Unsqueeze - adds `1` dimensions to a target tenson
* Permute - return a view of the input with dimensions permuted (swapped) in a certain way

In [ ]:
# Create a Tensor

x = torch.arange(start=1.,end=11.,step=1)
x, x.size()

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [ ]:
# Adding dimension
x_reshaped = x.reshape(1, 10)
x_reshaped, x_reshaped.size()

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [ ]:
# Adding multiple dimension
x_reshaped_multi = x.reshape(2, 5)
x_reshaped_multi, x_reshaped_multi.size()

(tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]),
 torch.Size([2, 5]))

In [ ]:
# Changing view
x_view = x.view(1, 10)
x_view, x_view.size()

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [ ]:
# View of a tensor uses same memory as the tensor itself
x_view[:, 0] = 12.
x_view, x

(tensor([[12.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 tensor([12.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [ ]:
# Stacking Tensors

# VStack
x_vstacked = torch.stack([x, x, x, x], dim=0)
print(f"Vertical Stack: {x_vstacked}")

#HStack
x_hstacked = torch.stack([x, x, x, x], dim=1)
print(f"Horizontal Stack: {x_hstacked}")

Vertical Stack: tensor([[12.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [12.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [12.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [12.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])
Horizontal Stack: tensor([[12., 12., 12., 12.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [10., 10., 10., 10.]])


In [ ]:
# Squeezing and Unsqueezing Tensors

# Squeezing Tensor -> Removes single dimension from the tensor
print("Squeezing Tensor: ")
print(f"=> X_Reshaped Size: {x_reshaped.size()}")
print(f"=> X_Reshaped Squeezed Size: {x_reshaped.squeeze().size()}")

# Unsqueezing Tensor -> Adds a single dimenson to a target tensor
print("\nUnsqueezing Tensor: ")
print(f"=> X_Reshaped Size: {x_reshaped.size()}")
print(f"=> X_Reshaped Unsqueezed Size: {x_reshaped.unsqueeze(dim=0).size()}")

Squeezing Tensor: 
=> X_Reshaped Size: torch.Size([1, 10])
=> X_Reshaped Squeezed Size: torch.Size([10])

Unsqueezing Tensor: 
=> X_Reshaped Size: torch.Size([1, 10])
=> X_Reshaped Unsqueezed Size: torch.Size([1, 1, 10])


In [ ]:
# torch.permute -> rearranges the dimension of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # height, width, color_channels

# Permute the original tensor to rearrange the axis (dimension) order
# Permute === View (same memory) as original tensor
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Original size: {x_original.size()}")
print(f"Permuted size: {x_permuted.size()}")

Original size: torch.Size([224, 224, 3])
Permuted size: torch.Size([3, 224, 224])


### Indexing

Indexing in PyTorch is similar to indexing in NumPY

In [ ]:
# Creating Tensor
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.size()

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Indexing on Tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Selecting all of the target dimension with ":"
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
# Get all values of 0th and 1st dimension but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
x[0][1][1]

tensor(5)

Finding the min, max, mean, sum, etc (tensor aggregatoin)

In [ ]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
torch.max(x), x.max() # max

(tensor(90), tensor(90))

In [ ]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean() # mean => torch.float32 (dtype)

(tensor(45.), tensor(45.))

In [ ]:
torch.sum(x), x.sum() # sum

(tensor(450), tensor(450))

Finding the positional min and max

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
x.argmin() # position in the tensor with min value (x[0] = 0 (lowest))

tensor(0)

In [ ]:
x.argmax() # position in the tensor with max value (x[9] = 90 (highest))

tensor(9)

PyTorch tensors and NumPy

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [ ]:
# NumPy arrat to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor, array.dtype

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64),
 dtype('float64'))

In [ ]:
# Tensor to NumPy array
tensor = torch.ones(6)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducbility (trying to take random out of random)

In show how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> loop...`

To reduce the randomness in neural networks and PyTorch, there comes one concept know as **random seed**.

Essentially what the random seed does is "flavour" the randomness.

In [ ]:
import torch

# Create two random tensors
rand_tensor_A = torch.rand(3, 4)
rand_tensor_B = torch.rand(3, 4)

print(rand_tensor_A)
print(rand_tensor_B)
print (rand_tensor_A == rand_tensor_B)

tensor([[0.1507, 0.3615, 0.9521, 0.2230],
        [0.8325, 0.7244, 0.7398, 0.9593],
        [0.1233, 0.7230, 0.9924, 0.0889]])
tensor([[0.2945, 0.1280, 0.8471, 0.3020],
        [0.4784, 0.1633, 0.9822, 0.5630],
        [0.8300, 0.7119, 0.3386, 0.3344]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Make some random, but reproducible tensors
import torch

# Set the random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
rand_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
rand_tensor_D = torch.rand(3, 4)

print(rand_tensor_C)
print(rand_tensor_D)
print(rand_tensor_C == rand_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs (making faster computations)

GPUs = faster computation on numbers, CUDA + NVIDA hardware + PyTorch

### 1. Getting a GPU

1. Easiest = Use Google COlab for a free GPU (Pro/Upgrade avaiable)
2. Own GPU = configurtion needed and High performance GPU required
3. Use Cloud computing - GCP, AWS, Azures, allows computers on rental basis

### 2. Check for GPU access with PyTorch

In [ ]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

In [ ]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# Count number of devices
torch.cuda.device_count()

1

### 3. Putting tensors (and models) on the GPU

In [ ]:
# Create a tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

#Tensor not on GPU
print (tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# Transfer tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensor back to the CPU

In [ ]:
tensor_on_gpu.numpy() # tensor under GPU, can't be transformed to NumPy

TypeError: ignored

In [ ]:
# Transfer to CPU, to tranform into NumPy
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [ ]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')