# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [11]:
# No code solution (reading) => DONE!

### 2. Create a random tensor with shape `(7, 7)`.


In [3]:
# Import torch
import torch;

# Create random tensor
x = torch.rand(7, 7);
x

tensor([[6.6902e-01, 4.0750e-02, 9.5594e-01, 7.3230e-01, 1.2338e-01, 3.8637e-01,
         7.7785e-01],
        [4.4464e-01, 2.7420e-01, 3.8223e-01, 1.7261e-01, 4.0348e-01, 4.2924e-02,
         1.8723e-01],
        [6.6532e-02, 4.2132e-01, 7.2517e-02, 1.4433e-02, 7.3250e-01, 8.9414e-01,
         8.0745e-02],
        [1.5314e-01, 1.5203e-01, 5.4707e-01, 6.1480e-01, 3.8773e-01, 7.0418e-01,
         4.5856e-01],
        [7.2078e-01, 8.8213e-02, 1.4472e-04, 4.7883e-01, 4.8788e-01, 8.8104e-01,
         4.1777e-01],
        [4.5211e-01, 3.8966e-01, 4.8509e-01, 1.0226e-01, 1.6235e-01, 6.0580e-02,
         7.5584e-01],
        [7.4759e-01, 5.5740e-01, 2.4767e-01, 7.8886e-01, 7.4519e-01, 5.9110e-01,
         7.5758e-01]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [4]:
# Create another random tensor
y = torch.rand(1, 7);
z = torch.transpose(y, 0, 1);
# Perform matrix multiplication
muled = torch.matmul(x, z)
print(f"Multiplied Matrix: \n{muled}");

Multiplied Matrix: 
tensor([[2.4096],
        [1.1563],
        [1.4855],
        [2.0528],
        [1.8983],
        [1.4600],
        [2.6994]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [5]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
x = torch.rand(7, 7);
y = torch.rand(1, 7);
z = torch.transpose(y, 0, 1);
# Matrix multiply tensors
muled = torch.matmul(x, z)
print(f"Multiplied Matrix: \n{muled} {muled.size()}");

Multiplied Matrix: 
tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]]) torch.Size([7, 1])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [6]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [7]:
from torch.cuda import is_available
# Set random seed
torch.cuda.manual_seed(1234)

# Check for access to GPU
device = "cuda" if (torch.cuda.is_available) else "cpu";
# Create two random tensors on GPU
tensor_x = torch.rand(2, 3);
tensor_y = torch.rand(2, 3);
tensor_x_gpu = tensor_x.to(device);
tensor_y_gpu = tensor_y.to(device);

print(f'''Device: {device}
      \n Tensor X (on GPU): {tensor_x_gpu}
      \n Tensor Y (on GPU): {tensor_y_gpu}''');

Device: cuda
      
 Tensor X (on GPU): tensor([[0.5932, 0.1123, 0.1535],
        [0.2417, 0.7262, 0.7011]], device='cuda:0')
      
 Tensor Y (on GPU): tensor([[0.2038, 0.6511, 0.7745],
        [0.4369, 0.5191, 0.6159]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [8]:
# Perform matmul on tensor_A and tensor_B
tensor_y_gpu_trans = torch.transpose(tensor_y_gpu, 1, 0);
matrix_multiplication = torch.matmul(tensor_x_gpu,
                                     tensor_y_gpu_trans);
print(f"Matrix Mulitplied: {matrix_multiplication} {matrix_multiplication.size()}");

Matrix Mulitplied: tensor([[0.3129, 0.4120],
        [1.0651, 0.9143]], device='cuda:0') torch.Size([2, 2])


### 8. Find the maximum and minimum values of the output of 7.

In [9]:
# Find max
print(f"Max: {matrix_multiplication.max()}");
# Find min
print(f"Min: {matrix_multiplication.min()}");

Max: 1.0650615692138672
Min: 0.31289684772491455


### 9. Find the maximum and minimum index values of the output of 7.

In [10]:
from numpy import unravel_index;

# Find arg max
print(f"Argumental Max: {matrix_multiplication.argmax()}")
# Find arg min
print(f"Argumental Min: {matrix_multiplication.argmin()}")

# Max Value from arg max
max_value = unravel_index(matrix_multiplication.cpu().argmax(), matrix_multiplication.cpu().shape);
print(f"Unravel Indexing (Max): {matrix_multiplication[max_value]}");
# # Min Value from arg min
min_value = unravel_index(matrix_multiplication.cpu().argmin(), matrix_multiplication.cpu().shape);
print(f"Unravel Indexing (Min): {matrix_multiplication[min_value]}");

Argumental Max: 2
Argumental Min: 0
Unravel Indexing (Max): 1.0650615692138672
Unravel Indexing (Min): 0.31289684772491455



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [15]:
# Set seed
torch.manual_seed(7)

# Create random tensor
rand_tensor = torch.rand(1, 1, 1, 10);

# Remove single dimensions
final_tensor = torch.squeeze(rand_tensor);

# Print out tensors and their shapes
print(f"Initial Random Tensor: {rand_tensor}\nInitial Size: {rand_tensor.size()}\nFinal Tensor: {final_tensor}\nFinal Size: {final_tensor.size()}");

Initial Random Tensor: tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
Initial Size: torch.Size([1, 1, 1, 10])
Final Tensor: tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
Final Size: torch.Size([10])
